version: '3.5'

services:
  mysql:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: cl
    ports:
      - 3306:3306
